version: '3.8'

services:
# Service 1 : Elasticsearch : moteur de recherche et d'analyse distribué, utilisé pour stocker et rechercher des données.
# Service 2 : Logstash : outil de collecte, de transformation et de transfert de données, utilisé pour ingérer des données dans Elasticsearch.
# Service 3 : Kibana : interface de visualisation et d'exploration de données, utilisée pour créer des tableaux de bord et des graphiques à partir des données stockées dans Elasticsearch.
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - es-data:/usr/share/elasticsearch/data

  logstash:
    image: docker.elastic.co/logstash/logstash:8.13.0
    container_name: logstash
    ports:
      - "5044:5044"
      - "5000:5000/udp"
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.0
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch

volumes:
  es-data: