input {
  udp {
    port => 5000
    codec => json
  }
}

filter {
  if [message] =~ "Résultat" {
    mutate { add_field => { "type" => "calcul" } }
  }
  if [message] =~ "Erreur" {
    mutate { add_field => { "type" => "erreur" } }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "calculator-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}